version: "3.8"

services:

  telemaster-mongo:
    container_name: telemaster-mongo
    image: mongo:latest
    volumes:
      - ./mongo-data:/data
    ports:
      - 27017:27017

  telemaster-api:
    container_name: telemaster-api
    image: node:latest
    user: node
    working_dir: /home/node/app
    environment:
      NODE_ENV: development
      MONGO_CONNECTION_STRING: mongodb://telemaster/masts
      MONGO_COLLECTION_NAME: masts
      MONGO_DB_NAME: telemaster
      PORT: 8000
    ports:
      - 8000:8000
    depends_on:
      - telemaster-mongo
    volumes:
      - ./api:/home/node/app
    command: yarn start
