name: CI 🤖

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v1
      with:
        node-version: '15'

    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

    - name: 📦 yarn install root 🦷
      run: yarn --frozen-lockfile

    - name: 📦 yarn install 🕸 app
      working-directory: ./webapp
      run: yarn --frozen-lockfile

    - name: 📦 yarn install 🅰🅿🅸
      working-directory: ./api
      run: yarn --frozen-lockfile

    - name: 🧼 linting
      run: yarn lint
